CREATE TABLE IF NOT EXISTS Usuarios(
id SERIAL,
nombre VARCHAR (100) NOT NULL,
password INT NULL,
edad INT NULL,
PRIMARY KEY (id)
 );

CREATE TABLE IF NOT EXISTS Padres(
id SERIAL,
nombres VARCHAR (100)  NULL,
cedula VARCHAR (100) NULL,
telefono VARCHAR (100) NULL,
PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS Docentes(
    id SERIAL,
    nombre VARCHAR (100) NULL,
    edad VARCHAR (100) NULL,
    PRIMARY KEY (id)

 );