CREATE TABLE IF NOT EXISTS Usuarios(
id SERIAL,
nombre VARCHAR (100) NOT NULL,
password INT NULL,
edad INT NULL,
PRIMARY KEY (id)
 );

CREATE TABLE IF NOT EXISTS Rutas(
id SERIAL,
nombreRutas VARCHAR (100)  NULL,
tiempoRutas VARCHAR (100) NULL,
PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS Camion(
    id SERIAL,
    horas VARCHAR (100) NULL,
    dias VARCHAR (100) NULL,
    PRIMARY KEY (id)

 );